server:
  port: 8081

spring:
  application:
    name: "auth-service"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:auth-db}
    username: ${DB_USERNAME:hieuminhle123}
    password: ${DB_PASSWORD:Password123@}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
