version: "3.8"

services:
  postgres:
    container_name: postgresSQL
    image: postgres:16-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    volumes:
      - pg_data_v2:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pg_data_v2:
    driver: local

