server:
  port: 8082

spring:
  application:
    name: "profile-service"

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:Password123}